[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    regress: Запускает регресс кейсы
    smoke: Запускает смоук кейсы
    registration: Запускает регистрации кейсы